/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define AIRMAN_ANIM_DEFAULTANIMATION 0
#define AIRMAN_ANIM_ATTACK01 1
#define AIRMAN_ANIM_ATTACK02 2
#define AIRMAN_ANIM_ATTACK03 3
#define AIRMAN_ANIM_ATTACK04 4
#define AIRMAN_ANIM_ATTACK05 5
#define AIRMAN_ANIM_ATTACK06 6
#define AIRMAN_ANIM_DEATH01 7
#define AIRMAN_ANIM_DEATH02 8
#define AIRMAN_ANIM_DEATH03 9
#define AIRMAN_ANIM_STANDBOX 10
#define AIRMAN_ANIM_MORPHBOXUP 11
#define AIRMAN_ANIM_MORPHBOXDOWN 12
#define AIRMAN_ANIM_STANDPLANE 13
#define AIRMAN_ANIM_MORPHPLANEUP 14
#define AIRMAN_ANIM_MORPHPLANEDOWN 15
#define AIRMAN_ANIM_RUN 16
#define AIRMAN_ANIM_STAND 17
#define AIRMAN_ANIM_WALK 18
#define AIRMAN_ANIM_WOUND01 19
#define AIRMAN_ANIM_WOUND02 20
#define AIRMAN_ANIM_WOUND03 21

// Color names
#define AIRMAN_PART_BODYDOWN ((1L) << 0)

// Patch names

// Names of collision boxes
#define AIRMAN_COLLISION_BOX_NORMAL 0
#define AIRMAN_COLLISION_BOX_BOX 1

// Attaching position names
#define AIRMAN_ATTACHMENT_TWISTER 0

// Sound names
