/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define STONEMAN_ANIM_DEFAULTANIMATION 0
#define STONEMAN_ANIM_ATTACK01 1
#define STONEMAN_ANIM_ATTACK02 2
#define STONEMAN_ANIM_ATTACK03 3
#define STONEMAN_ANIM_ATTACK04 4
#define STONEMAN_ANIM_ATTACK05 5
#define STONEMAN_ANIM_ATTACK06 6
#define STONEMAN_ANIM_DEATH01 7
#define STONEMAN_ANIM_DEATH02 8
#define STONEMAN_ANIM_DEATH03 9
#define STONEMAN_ANIM_STANDBOX 10
#define STONEMAN_ANIM_MORPHBOXUP 11
#define STONEMAN_ANIM_MORPHBOXDOWN 12
#define STONEMAN_ANIM_STANDPLANE 13
#define STONEMAN_ANIM_MORPHPLANEUP 14
#define STONEMAN_ANIM_MORPHPLANEDOWN 15
#define STONEMAN_ANIM_RUN 16
#define STONEMAN_ANIM_STAND 17
#define STONEMAN_ANIM_WALK 18
#define STONEMAN_ANIM_WOUND01 19
#define STONEMAN_ANIM_WOUND02 20
#define STONEMAN_ANIM_WOUND03 21

// Color names

// Patch names

// Names of collision boxes
#define STONEMAN_COLLISION_BOX_NORMAL 0
#define STONEMAN_COLLISION_BOX_BOX 1

// Attaching position names
#define STONEMAN_ATTACHMENT_MAUL 0

// Sound names
