/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define PLAYER_ANIM_DEFAULT_ANIMATION 0
#define PLAYER_ANIM_STAND 1
#define PLAYER_ANIM_WALK 2
#define PLAYER_ANIM_WALKBACK 3
#define PLAYER_ANIM_WALKBACK_FAST 4
#define PLAYER_ANIM_CROUCHWALK 5
#define PLAYER_ANIM_CROUCHWALKBACK 6
#define PLAYER_ANIM_SWIM 7
#define PLAYER_ANIM_SWIMIDLE 8
#define PLAYER_ANIM_CROUCH 9
#define PLAYER_ANIM_CROUCHIDLE 10
#define PLAYER_ANIM_RISE 11
#define PLAYER_ANIM_DEATH01 12
#define PLAYER_ANIM_JUMPSTART 13
#define PLAYER_ANIM_JUMPEND 14
#define PLAYER_ANIM_RUN 15
#define PLAYER_ANIM_RUNBACK 16
#define PLAYER_ANIM_TURNLEFT 17
#define PLAYER_ANIM_TURNRIGHT 18
#define PLAYER_ANIM_CROUCHTURNLEFT 19
#define PLAYER_ANIM_CROUCHTURNRIGHT 20
#define PLAYER_ANIM_DEATH_UNDERWATER 21
#define PLAYER_ANIM_DEATH_SPIKES 22
#define PLAYER_ANIM_STATUE_PULL 23

// Color names

// Patch names

// Names of collision boxes
#define PLAYER_COLLISION_BOX_STAND 0
#define PLAYER_COLLISION_BOX_CROUCH 1
#define PLAYER_COLLISION_BOX_SWIM 2

// Attaching position names
#define PLAYER_ATTACHMENT_TORSO 0

// Sound names
