/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define BONEMAN_ANIM_DEFAULT_ANIMATION 0
#define BONEMAN_ANIM_ATTACKCLOSELOOP 1
#define BONEMAN_ANIM_ATTACKFAR 2
#define BONEMAN_ANIM_DEATHTOBACK 3
#define BONEMAN_ANIM_DEATHTOFRONT 4
#define BONEMAN_ANIM_FALL01 5
#define BONEMAN_ANIM_FALL02 6
#define BONEMAN_ANIM_RUNLOOP 7
#define BONEMAN_ANIM_STANDLOOP 8
#define BONEMAN_ANIM_WALKLOOP 9
#define BONEMAN_ANIM_WOUNDCRITICAL01 10
#define BONEMAN_ANIM_WOUNDCRITICAL02 11
#define BONEMAN_ANIM_WOUNDCRITICAL03 12
#define BONEMAN_ANIM_JUMPTOWALL 13
#define BONEMAN_ANIM_WALKCOMPUTER 14

// Color names

// Patch names

// Names of collision boxes
#define BONEMAN_COLLISION_BOX_DEFAULT 0
#define BONEMAN_COLLISION_BOX_DEATH 1

// Attaching position names

// Sound names
