/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define BODY_ANIM_MINIGUN_FIRESHORT 0

// Color names

// Patch names

// Names of collision boxes
#define BODY_COLLISION_BOX_STAND 0

// Attaching position names
#define BODY_ATTACHMENT_HEAD 0
#define BODY_ATTACHMENT_COLT_RIGHT 1
#define BODY_ATTACHMENT_KNIFE 2
#define BODY_ATTACHMENT_SINGLE_SHOTGUN 3
#define BODY_ATTACHMENT_DOUBLE_SHOTGUN 4
#define BODY_ATTACHMENT_FLAMER 5
#define BODY_ATTACHMENT_TOMMYGUN 6
#define BODY_ATTACHMENT_CANNON 7
#define BODY_ATTACHMENT_GRENADE_LAUNCHER 8
#define BODY_ATTACHMENT_LASER 9
#define BODY_ATTACHMENT_MINIGUN 10
#define BODY_ATTACHMENT_ROCKET_LAUNCHER 11
#define BODY_ATTACHMENT_COLT_LEFT 12
#define BODY_ATTACHMENT_ITEM 13

// Sound names
