/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define ICEMAN_ANIM_DEFAULTANIMATION 0
#define ICEMAN_ANIM_ATTACK01 1
#define ICEMAN_ANIM_ATTACK02 2
#define ICEMAN_ANIM_ATTACK03 3
#define ICEMAN_ANIM_ATTACK04 4
#define ICEMAN_ANIM_ATTACK05 5
#define ICEMAN_ANIM_ATTACK06 6
#define ICEMAN_ANIM_DEATH01 7
#define ICEMAN_ANIM_DEATH02 8
#define ICEMAN_ANIM_DEATH03 9
#define ICEMAN_ANIM_STANDBOX 10
#define ICEMAN_ANIM_MORPHBOXUP 11
#define ICEMAN_ANIM_MORPHBOXDOWN 12
#define ICEMAN_ANIM_STANDPLANE 13
#define ICEMAN_ANIM_MORPHPLANEUP 14
#define ICEMAN_ANIM_MORPHPLANEDOWN 15
#define ICEMAN_ANIM_RUN 16
#define ICEMAN_ANIM_STAND 17
#define ICEMAN_ANIM_WALK 18
#define ICEMAN_ANIM_WOUND01 19
#define ICEMAN_ANIM_WOUND02 20
#define ICEMAN_ANIM_WOUND03 21

// Color names

// Patch names

// Names of collision boxes
#define ICEMAN_COLLISION_BOX_NORMAL 0
#define ICEMAN_COLLISION_BOX_BOX 1

// Attaching position names
#define ICEMAN_ATTACHMENT_ICEPICK 0

// Sound names
