/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define WATERMAN_ANIM_DEFAULTANIMATION 0
#define WATERMAN_ANIM_ATTACK01 1
#define WATERMAN_ANIM_ATTACK02 2
#define WATERMAN_ANIM_ATTACK03 3
#define WATERMAN_ANIM_ATTACK04 4
#define WATERMAN_ANIM_ATTACK05 5
#define WATERMAN_ANIM_ATTACK06 6
#define WATERMAN_ANIM_DEATH01 7
#define WATERMAN_ANIM_DEATH02 8
#define WATERMAN_ANIM_DEATH03 9
#define WATERMAN_ANIM_STANDBOX 10
#define WATERMAN_ANIM_MORPHBOXUP 11
#define WATERMAN_ANIM_MORPHBOXDOWN 12
#define WATERMAN_ANIM_STANDPLANE 13
#define WATERMAN_ANIM_MORPHPLANEUP 14
#define WATERMAN_ANIM_MORPHPLANEDOWN 15
#define WATERMAN_ANIM_RUN 16
#define WATERMAN_ANIM_STAND 17
#define WATERMAN_ANIM_WALK 18
#define WATERMAN_ANIM_WOUND01 19
#define WATERMAN_ANIM_WOUND02 20
#define WATERMAN_ANIM_WOUND03 21

// Color names

// Patch names

// Names of collision boxes
#define WATERMAN_COLLISION_BOX_NORMAL 0
#define WATERMAN_COLLISION_BOX_BOX 1

// Attaching position names
#define WATERMAN_ATTACHMENT_BODY_FLARE 0

// Sound names
