/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define HANDWITHBOMB_ANIM_DEFAULT_ANIMATION 0
#define HANDWITHBOMB_ANIM_ACTIVATE 1
#define HANDWITHBOMB_ANIM_DEACTIVATE 2
#define HANDWITHBOMB_ANIM_BOMBTHROW1 3
#define HANDWITHBOMB_ANIM_BOMBTHROW2 4
#define HANDWITHBOMB_ANIM_BOMBWAIT1 5
#define HANDWITHBOMB_ANIM_BOMBWAIT2 6
#define HANDWITHBOMB_ANIM_BOMBWAIT3 7
#define HANDWITHBOMB_ANIM_BOMBWAIT4 8
#define HANDWITHBOMB_ANIM_BOMBWAIT5 9

// Color names

// Patch names

// Names of collision boxes
#define HANDWITHBOMB_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define HANDWITHBOMB_ATTACHMENT_BOMB 0

// Sound names
