/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define HANDWITHSTICK_ANIM_DEFAULT_ANIMATION 0
#define HANDWITHSTICK_ANIM_STICKFIRE 1
#define HANDWITHSTICK_ANIM_ACTIVATE 2
#define HANDWITHSTICK_ANIM_DEACTIVATE 3
#define HANDWITHSTICK_ANIM_STICKTHROW 4
#define HANDWITHSTICK_ANIM_STICKRETURN 5
#define HANDWITHSTICK_ANIM_STICKTHROWWAIT1 6
#define HANDWITHSTICK_ANIM_STICKTHROWWAIT2 7
#define HANDWITHSTICK_ANIM_STICKTHROWWAIT3 8
#define HANDWITHSTICK_ANIM_STICKWAIT1 9
#define HANDWITHSTICK_ANIM_STICKWAIT2 10
#define HANDWITHSTICK_ANIM_STICKWAIT3 11
#define HANDWITHSTICK_ANIM_STICKWAIT4 12

// Color names

// Patch names

// Names of collision boxes
#define HANDWITHSTICK_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define HANDWITHSTICK_ATTACHMENT_STICK 0
#define HANDWITHSTICK_ATTACHMENT_SHIELD 1
#define HANDWITHSTICK_ATTACHMENT_BUTTON 2

// Sound names
