/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define ITEMHOLDER_ANIM_DEFAULT_ANIMATION 0
#define ITEMHOLDER_ANIM_SMALLOSCILATION 1
#define ITEMHOLDER_ANIM_MEDIUMOSCILATION 2
#define ITEMHOLDER_ANIM_BIGOSCILATION 3

// Color names

// Patch names

// Names of collision boxes
#define ITEMHOLDER_COLLISION_BOX_SMALL 0
#define ITEMHOLDER_COLLISION_BOX_MEDIUM 1
#define ITEMHOLDER_COLLISION_BOX_BIG 2

// Attaching position names
#define ITEMHOLDER_ATTACHMENT_ITEM 0
#define ITEMHOLDER_ATTACHMENT_WEAPON 1
#define ITEMHOLDER_ATTACHMENT_FLARE 2
#define ITEMHOLDER_ATTACHMENT_SUPERHELMET 3
#define ITEMHOLDER_ATTACHMENT_SUPERARMOR 4
#define ITEMHOLDER_ATTACHMENT_SUPERSHIELD 5

// Sound names
