/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define HEADMANTEST_ANIM_DEFAULT_ANIMATION 0
#define HEADMANTEST_ANIM_COMPUTER 1
#define HEADMANTEST_ANIM_COMPUTERKAMIKAZE 2
#define HEADMANTEST_ANIM_FIRECRACKER_ATTACK 3
#define HEADMANTEST_ANIM_ROCKETMAN_ATTACK 4
#define HEADMANTEST_ANIM_BOMBERMAN_ATTACK 5
#define HEADMANTEST_ANIM_KAMIKAZE_ATTACK 6
#define HEADMANTEST_ANIM_DEATH_FALL_BACK 7
#define HEADMANTEST_ANIM_DEATH_FALL_ON_KNEES 8
#define HEADMANTEST_ANIM_DEATH_EASY_FALL_FORWARD 9
#define HEADMANTEST_ANIM_DEATH_EASY_FALL_BACK 10
#define HEADMANTEST_ANIM_WOUND1 11
#define HEADMANTEST_ANIM_WOUND2 12
#define HEADMANTEST_ANIM_RUN 13
#define HEADMANTEST_ANIM_IDLE_FIGHT 14
#define HEADMANTEST_ANIM_IDLE_PATROL 15
#define HEADMANTEST_ANIM_WALK 16

// Color names

// Patch names

// Names of collision boxes
#define HEADMANTEST_COLLISION_BOX_DEFAULT 0
#define HEADMANTEST_COLLISION_BOX_DEATH 1

// Attaching position names

// Sound names
