/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define GHOSTBUSTER_ANIM_DEFAULT 0
#define GHOSTBUSTER_ANIM_FIRE 1
#define GHOSTBUSTER_ANIM_ACTIVATE 2
#define GHOSTBUSTER_ANIM_DEACTIVATE 3
#define GHOSTBUSTER_ANIM_WAIT01 4
#define GHOSTBUSTER_ANIM_WAIT02 5
#define GHOSTBUSTER_ANIM_WAIT03 6
#define GHOSTBUSTER_ANIM_WAIT04 7

// Color names

// Patch names

// Names of collision boxes
#define GHOSTBUSTER_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define GHOSTBUSTER_ATTACHMENT_BODY 0
#define GHOSTBUSTER_ATTACHMENT_ROTATOR 1
#define GHOSTBUSTER_ATTACHMENT_EFFECT01 2
#define GHOSTBUSTER_ATTACHMENT_EFFECT02 3
#define GHOSTBUSTER_ATTACHMENT_EFFECT03 4
#define GHOSTBUSTER_ATTACHMENT_EFFECT04 5

// Sound names
