/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define EYEMAN_ANIM_DEFAULT_ANIMATION 0
#define EYEMAN_ANIM_MORPHUP 1
#define EYEMAN_ANIM_MORPHDOWN 2
#define EYEMAN_ANIM_ATTACK01 3
#define EYEMAN_ANIM_ATTACK02 4
#define EYEMAN_ANIM_MORPHSTAND 5
#define EYEMAN_ANIM_MORPHATTACK 6
#define EYEMAN_ANIM_MORPHATTACKFLY 7
#define EYEMAN_ANIM_DEATH01 8
#define EYEMAN_ANIM_DEATH01REST 9
#define EYEMAN_ANIM_DEATH02 10
#define EYEMAN_ANIM_DEATH02REST 11
#define EYEMAN_ANIM_MORPHDEATH 12
#define EYEMAN_ANIM_MORPHDEATHRESTFRAME 13
#define EYEMAN_ANIM_FALL01 14
#define EYEMAN_ANIM_FALL02 15
#define EYEMAN_ANIM_RUN 16
#define EYEMAN_ANIM_STAND 17
#define EYEMAN_ANIM_WALK 18
#define EYEMAN_ANIM_WOUND03 19
#define EYEMAN_ANIM_WOUND06 20
#define EYEMAN_ANIM_WOUND07 21
#define EYEMAN_ANIM_MORPHWOUND01 22
#define EYEMAN_ANIM_MORPHWOUND02 23
#define EYEMAN_ANIM_IDLECOMPUTER 24

// Color names

// Patch names

// Names of collision boxes
#define EYEMAN_COLLISION_BOX_GROUND 0
#define EYEMAN_COLLISION_BOX_AIR 1
#define EYEMAN_COLLISION_BOX_DEATH 2

// Attaching position names

// Sound names
