/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define ROCKETLAUNCHER_ANIM_CENTERED 0
#define ROCKETLAUNCHER_ANIM_FIREPART1 1
#define ROCKETLAUNCHER_ANIM_FIREPART2 2
#define ROCKETLAUNCHER_ANIM_FIRE 3
#define ROCKETLAUNCHER_ANIM_WAIT1 4
#define ROCKETLAUNCHER_ANIM_WAIT2 5
#define ROCKETLAUNCHER_ANIM_ACTIVATE 6
#define ROCKETLAUNCHER_ANIM_DEACTIVATE 7

// Color names

// Patch names

// Names of collision boxes
#define ROCKETLAUNCHER_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define ROCKETLAUNCHER_ATTACHMENT_BODY 0
#define ROCKETLAUNCHER_ATTACHMENT_ROTATINGPART 1
#define ROCKETLAUNCHER_ATTACHMENT_ROCKET1 2
#define ROCKETLAUNCHER_ATTACHMENT_ROCKET2 3
#define ROCKETLAUNCHER_ATTACHMENT_ROCKET3 4

// Sound names
