/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define GHOSTBUSTERITEM_ANIM_CENTERED 0

// Color names

// Patch names

// Names of collision boxes
#define GHOSTBUSTERITEM_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define GHOSTBUSTERITEM_ATTACHMENT_BODY 0
#define GHOSTBUSTERITEM_ATTACHMENT_ROTATOR 1
#define GHOSTBUSTERITEM_ATTACHMENT_EFFECT01 2
#define GHOSTBUSTERITEM_ATTACHMENT_EFFECT02 3
#define GHOSTBUSTERITEM_ATTACHMENT_EFFECT03 4
#define GHOSTBUSTERITEM_ATTACHMENT_EFFECT04 5

// Sound names
