/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define CYBORG_ANIM_DEFAULT_ANIMATION 0
#define CYBORG_ANIM_ATTACKCLOSE01 1
#define CYBORG_ANIM_ATTACKCLOSE02 2
#define CYBORG_ANIM_DEATH01 3
#define CYBORG_ANIM_DEATH02 4
#define CYBORG_ANIM_DEATHREST 5
#define CYBORG_ANIM_DEATHTWIST 6
#define CYBORG_ANIM_TOFIRE 7
#define CYBORG_ANIM_FIRE01 8
#define CYBORG_ANIM_FIRE02 9
#define CYBORG_ANIM_FIRE01SLIDE 10
#define CYBORG_ANIM_FIRE02SLIDE 11
#define CYBORG_ANIM_FROMFIRE 12
#define CYBORG_ANIM_WAIT01 13
#define CYBORG_ANIM_WAIT02 14
#define CYBORG_ANIM_WAIT03 15
#define CYBORG_ANIM_WALK01 16
#define CYBORG_ANIM_WALK02 17
#define CYBORG_ANIM_WOUND01 18
#define CYBORG_ANIM_WOUND02 19
#define CYBORG_ANIM_WOUND03 20
#define CYBORG_ANIM_WOUND04 21

// Color names

// Patch names

// Names of collision boxes
#define CYBORG_COLLISION_BOX_PART_NAME 0

// Attaching position names

// Sound names
