/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define DOUBLESHOTGUN_ANIM_DEFAULT_ANIMATION 0
#define DOUBLESHOTGUN_ANIM_FIRE 1
#define DOUBLESHOTGUN_ANIM_WAIT1 2
#define DOUBLESHOTGUN_ANIM_WAIT2 3
#define DOUBLESHOTGUN_ANIM_WAIT3 4
#define DOUBLESHOTGUN_ANIM_WAIT4 5
#define DOUBLESHOTGUN_ANIM_ACTIVATE 6
#define DOUBLESHOTGUN_ANIM_DEACTIVATE 7

// Color names

// Patch names

// Names of collision boxes
#define DOUBLESHOTGUN_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define DOUBLESHOTGUN_ATTACHMENT_HANDLE 0
#define DOUBLESHOTGUN_ATTACHMENT_BARRELS 1
#define DOUBLESHOTGUN_ATTACHMENT_SWITCH 2
#define DOUBLESHOTGUN_ATTACHMENT_AMMO 3

// Sound names
