/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define ROCKETLAUNCHERITEM_ANIM_DEFAULT_ANIMATION 0

// Color names

// Patch names

// Names of collision boxes
#define ROCKETLAUNCHERITEM_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define ROCKETLAUNCHERITEM_ATTACHMENT_BODY 0
#define ROCKETLAUNCHERITEM_ATTACHMENT_ROTATINGPART 1
#define ROCKETLAUNCHERITEM_ATTACHMENT_ROCKET1 2
#define ROCKETLAUNCHERITEM_ATTACHMENT_ROCKET2 3
#define ROCKETLAUNCHERITEM_ATTACHMENT_ROCKET3 4
#define ROCKETLAUNCHERITEM_ATTACHMENT_ROCKET4 5

// Sound names
