/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define SCORPMAN_ANIM_DEFAULT_ANIMATION 0
#define SCORPMAN_ANIM_WALK 1
#define SCORPMAN_ANIM_WALK_AND_FIRE 2
#define SCORPMAN_ANIM_FIRE_MINIGUN 3
#define SCORPMAN_ANIM_SPIKEHIT 4
#define SCORPMAN_ANIM_DEATH 5
#define SCORPMAN_ANIM_IDLE 6
#define SCORPMAN_ANIM_SLEEP 7
#define SCORPMAN_ANIM_WAKEUP 8
#define SCORPMAN_ANIM_STANDTOFIRE 9
#define SCORPMAN_ANIM_FIRETOSTAND 10
#define SCORPMAN_ANIM_WOUND01 11
#define SCORPMAN_ANIM_WOUND02 12
#define SCORPMAN_ANIM_WOUND03 13

// Color names

// Patch names

// Names of collision boxes
#define SCORPMAN_COLLISION_BOX_DEFAULT 0
#define SCORPMAN_COLLISION_BOX_DEATH 1

// Attaching position names
#define SCORPMAN_ATTACHMENT_MINIGUN 0

// Sound names
