/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define SPACESHIP_ANIM_DEFAULT 0
#define SPACESHIP_ANIM_OPENING 1
#define SPACESHIP_ANIM_CLOSING 2
#define SPACESHIP_ANIM_OPEN 3

// Color names

// Patch names

// Names of collision boxes
#define SPACESHIP_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define SPACESHIP_ATTACHMENT_BODY 0
#define SPACESHIP_ATTACHMENT_BEAM 1
#define SPACESHIP_ATTACHMENT_BEAM_RIM 2
#define SPACESHIP_ATTACHMENT_DOOR1 3
#define SPACESHIP_ATTACHMENT_DOOR2 4
#define SPACESHIP_ATTACHMENT_DOOR3 5
#define SPACESHIP_ATTACHMENT_DOOR4 6
#define SPACESHIP_ATTACHMENT_DOOR5 7
#define SPACESHIP_ATTACHMENT_DOOR6 8
#define SPACESHIP_ATTACHMENT_DOOR7 9
#define SPACESHIP_ATTACHMENT_DOOR8 10
#define SPACESHIP_ATTACHMENT_SHIPINSIDE 11

// Sound names
