/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define ELEMENTALLAVA_ANIM_IDLE 0
#define ELEMENTALLAVA_ANIM_STANDFIGHT 1
#define ELEMENTALLAVA_ANIM_STANDPLANE 2
#define ELEMENTALLAVA_ANIM_ATTACKLEFTHAND 3
#define ELEMENTALLAVA_ANIM_ATTACKTWOHANDS 4
#define ELEMENTALLAVA_ANIM_WOUND01 5
#define ELEMENTALLAVA_ANIM_WOUND02 6
#define ELEMENTALLAVA_ANIM_WOUND03 7
#define ELEMENTALLAVA_ANIM_WALKBIG 8
#define ELEMENTALLAVA_ANIM_RUNSMALL 9
#define ELEMENTALLAVA_ANIM_RUNMEDIUM 10
#define ELEMENTALLAVA_ANIM_ANGER 11
#define ELEMENTALLAVA_ANIM_DEATH03 12
#define ELEMENTALLAVA_ANIM_MELTFLY 13
#define ELEMENTALLAVA_ANIM_MELTUP 14

// Color names

// Patch names

// Names of collision boxes
#define ELEMENTALLAVA_COLLISION_BOX_NORMAL  0
#define ELEMENTALLAVA_COLLISION_BOX_BOX 1

// Attaching position names
#define ELEMENTALLAVA_ATTACHMENT_BODY_FLARE 0
#define ELEMENTALLAVA_ATTACHMENT_RIGHT_HAND_FLARE 1
#define ELEMENTALLAVA_ATTACHMENT_LEFT_HAND_FLARE 2

// Sound names
