/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_AirShockwave_INCLUDED
#define _EntitiesMP_AirShockwave_INCLUDED 1
#include <EntitiesMP/BasicEffects.h>
#define EVENTCODE_EAirShockwave 0x015d0000
class DECL_DLL EAirShockwave : public CEntityEvent {
public:
EAirShockwave();
CEntityEvent *MakeCopy(void);
CEntityPointer penLauncher;
FLOAT fHeight;
FLOAT fEndWidth;
FLOAT fDuration;
};
DECL_DLL inline void ClearToDefault(EAirShockwave &e) { e = EAirShockwave(); } ;
extern "C" DECL_DLL CDLLEntityClass CAirShockwave_DLLClass;
class CAirShockwave : public CMovableModelEntity {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  CEntityPointer m_penLauncher;
  FLOAT m_fHeight;
  FLOAT m_fEndWidth;
  FLOAT m_tmBegin;
  FLOAT m_tmEnd;
  FLOAT m_fDuration;
  BOOL m_bGrowing;
  FLOAT m_tmLastGrow;
  FLOAT m_fFadeStartTime;
  FLOAT m_fFadeStartPercent;
  FLOAT m_fStretchY;
  FLOAT m_fBeginStretchXZ;
  FLOAT m_fEndStretchXZ;
  FLOATaabbox3D m_boxMaxSize;
  BOOL m_bFadeOut;
   
#line 71 "D:/SE1_GPL/Sources/EntitiesMP/AirShockwave.es"
CModelObject * ShockwaveModel(void);
   
#line 77 "D:/SE1_GPL/Sources/EntitiesMP/AirShockwave.es"
BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   
#line 112 "D:/SE1_GPL/Sources/EntitiesMP/AirShockwave.es"
void LaunchEntity(CEntity * pen);
   
#line 128 "D:/SE1_GPL/Sources/EntitiesMP/AirShockwave.es"
void TestForCollisionAndLaunchEntity();
#define  STATE_CAirShockwave_Main 1
  BOOL 
#line 158 "D:/SE1_GPL/Sources/EntitiesMP/AirShockwave.es"
Main(const CEntityEvent &__eeInput);
  BOOL H0x015d0001_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x015d0002_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x015d0003_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x015d0004_Main_04(const CEntityEvent &__eeInput);
  BOOL H0x015d0005_Main_05(const CEntityEvent &__eeInput);
  BOOL H0x015d0006_Main_06(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_AirShockwave_INCLUDED
