/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Beast_INCLUDED
#define _EntitiesMP_Beast_INCLUDED 1
#include <EntitiesMP/EnemyBase.h>
#include <EntitiesMP/BasicEffects.h>
extern DECL_DLL CEntityPropertyEnumType BeastType_enum;
enum BeastType {
  BT_NORMAL = 0,
  BT_BIG = 1,
  BT_HUGE = 2,
};
DECL_DLL inline void ClearToDefault(BeastType &e) { e = (BeastType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CBeast_DLLClass;
class CBeast : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum BeastType m_bcType;
  INDEX m_iCounter;
  BOOL m_bBeBoss;
  
#line 76 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
  
#line 82 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
virtual const CTFileName & GetComputerMessageName(void)const;
   
#line 93 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void Precache(void);
   
#line 114 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void * GetEntityInfo(void);
   
#line 124 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void ShakeItBaby(FLOAT tmShaketime,FLOAT fPower);
   
#line 144 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
FLOAT GetCrushHealth(void);
   
#line 154 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
BOOL ForcesCannonballToExplode(void);
   
#line 160 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 161 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 184 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
INDEX AnimForDamage(FLOAT fDamage);
   
#line 196 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
INDEX AnimForDeath(void);
   
#line 208 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
FLOAT WaitForDust(FLOAT3D & vStretch);
   
#line 217 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void DeathNotify(void);
   
#line 223 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void StandingAnim(void);
   
#line 228 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void WalkingAnim(void);
   
#line 242 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void RunningAnim(void);
   
#line 245 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void RotatingAnim(void);
   
#line 250 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void IdleSound(void);
   
#line 253 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void SightSound(void);
   
#line 256 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void WoundSound(void);
   
#line 263 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void DeathSound(void);
   
#line 273 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
void EnemyPostInit(void);
#define  STATE_CBeast_Death 0x01500000
  BOOL 
#line 282 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
Death(const CEntityEvent &__eeInput);
  BOOL H0x01500001_Death_01(const CEntityEvent &__eeInput);
  BOOL H0x01500002_Death_02(const CEntityEvent &__eeInput);
  BOOL H0x01500003_Death_03(const CEntityEvent &__eeInput);
  BOOL H0x01500004_Death_04(const CEntityEvent &__eeInput);
  BOOL H0x01500005_Death_05(const CEntityEvent &__eeInput);
  BOOL H0x01500006_Death_06(const CEntityEvent &__eeInput);
#define  STATE_CBeast_Fire 0x01500007
  BOOL 
#line 333 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
Fire(const CEntityEvent &__eeInput);
  BOOL H0x01500008_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x01500009_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x0150000a_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x0150000b_Fire_04(const CEntityEvent &__eeInput);
  BOOL H0x0150000c_Fire_05(const CEntityEvent &__eeInput);
  BOOL H0x0150000d_Fire_06(const CEntityEvent &__eeInput);
  BOOL H0x0150000e_Fire_07(const CEntityEvent &__eeInput);
  BOOL H0x0150000f_Fire_08(const CEntityEvent &__eeInput);
  BOOL H0x01500010_Fire_09(const CEntityEvent &__eeInput);
  BOOL H0x01500011_Fire_10(const CEntityEvent &__eeInput);
  BOOL H0x01500012_Fire_11(const CEntityEvent &__eeInput);
  BOOL H0x01500013_Fire_12(const CEntityEvent &__eeInput);
  BOOL H0x01500014_Fire_13(const CEntityEvent &__eeInput);
  BOOL H0x01500015_Fire_14(const CEntityEvent &__eeInput);
  BOOL H0x01500016_Fire_15(const CEntityEvent &__eeInput);
  BOOL H0x01500017_Fire_16(const CEntityEvent &__eeInput);
  BOOL H0x01500018_Fire_17(const CEntityEvent &__eeInput);
  BOOL H0x01500019_Fire_18(const CEntityEvent &__eeInput);
  BOOL H0x0150001a_Fire_19(const CEntityEvent &__eeInput);
  BOOL H0x0150001b_Fire_20(const CEntityEvent &__eeInput);
  BOOL H0x0150001c_Fire_21(const CEntityEvent &__eeInput);
  BOOL H0x0150001d_Fire_22(const CEntityEvent &__eeInput);
  BOOL H0x0150001e_Fire_23(const CEntityEvent &__eeInput);
  BOOL H0x0150001f_Fire_24(const CEntityEvent &__eeInput);
  BOOL H0x01500020_Fire_25(const CEntityEvent &__eeInput);
  BOOL H0x01500021_Fire_26(const CEntityEvent &__eeInput);
  BOOL H0x01500022_Fire_27(const CEntityEvent &__eeInput);
  BOOL H0x01500023_Fire_28(const CEntityEvent &__eeInput);
  BOOL H0x01500024_Fire_29(const CEntityEvent &__eeInput);
  BOOL H0x01500025_Fire_30(const CEntityEvent &__eeInput);
  BOOL H0x01500026_Fire_31(const CEntityEvent &__eeInput);
  BOOL H0x01500027_Fire_32(const CEntityEvent &__eeInput);
  BOOL H0x01500028_Fire_33(const CEntityEvent &__eeInput);
  BOOL H0x01500029_Fire_34(const CEntityEvent &__eeInput);
  BOOL H0x0150002a_Fire_35(const CEntityEvent &__eeInput);
  BOOL H0x0150002b_Fire_36(const CEntityEvent &__eeInput);
  BOOL H0x0150002c_Fire_37(const CEntityEvent &__eeInput);
  BOOL H0x0150002d_Fire_38(const CEntityEvent &__eeInput);
  BOOL H0x0150002e_Fire_39(const CEntityEvent &__eeInput);
  BOOL H0x0150002f_Fire_40(const CEntityEvent &__eeInput);
  BOOL H0x01500030_Fire_41(const CEntityEvent &__eeInput);
  BOOL H0x01500031_Fire_42(const CEntityEvent &__eeInput);
  BOOL H0x01500032_Fire_43(const CEntityEvent &__eeInput);
  BOOL H0x01500033_Fire_44(const CEntityEvent &__eeInput);
  BOOL H0x01500034_Fire_45(const CEntityEvent &__eeInput);
  BOOL H0x01500035_Fire_46(const CEntityEvent &__eeInput);
  BOOL H0x01500036_Fire_47(const CEntityEvent &__eeInput);
#define  STATE_CBeast_Hit 0x01500037
  BOOL 
#line 453 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
Hit(const CEntityEvent &__eeInput);
  BOOL H0x01500038_Hit_01(const CEntityEvent &__eeInput);
  BOOL H0x01500039_Hit_02(const CEntityEvent &__eeInput);
  BOOL H0x0150003a_Hit_03(const CEntityEvent &__eeInput);
  BOOL H0x0150003b_Hit_04(const CEntityEvent &__eeInput);
#define  STATE_CBeast_Main 1
  BOOL 
#line 486 "D:/SE1_GPL/Sources/EntitiesMP/Beast.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Beast_INCLUDED
