/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Headman_INCLUDED
#define _EntitiesMP_Headman_INCLUDED 1
#include <EntitiesMP/EnemyBase.h>
#include <EntitiesMP/BasicEffects.h>
extern DECL_DLL CEntityPropertyEnumType HeadmanType_enum;
enum HeadmanType {
  HDT_FIRECRACKER = 0,
  HDT_ROCKETMAN = 1,
  HDT_BOMBERMAN = 2,
  HDT_KAMIKAZE = 3,
};
DECL_DLL inline void ClearToDefault(HeadmanType &e) { e = (HeadmanType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CHeadman_DLLClass;
class CHeadman : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum HeadmanType m_hdtType;
  BOOL m_bExploded;
  BOOL m_bAttackSound;
  
#line 86 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
virtual CTString GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath);
   
#line 104 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void * GetEntityInfo(void);
  
#line 108 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
virtual const CTFileName & GetComputerMessageName(void)const;
   
#line 122 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void Precache(void);
   
#line 155 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
BOOL FillEntityStatistics(EntityStats * pes);
   
#line 168 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 169 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 187 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
INDEX AnimForDamage(FLOAT fDamage);
   
#line 199 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
INDEX AnimForDeath(void);
   
#line 222 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
FLOAT WaitForDust(FLOAT3D & vStretch);
   
#line 248 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
BOOL ShouldBlowUp(void);
   
#line 257 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void DeathNotify(void);
   
#line 263 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void StandingAnim(void);
   
#line 269 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void StandingAnimFight(void);
   
#line 276 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void WalkingAnim(void);
   
#line 279 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void RunningAnim(void);
   
#line 287 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void RotatingAnim(void);
   
#line 292 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void IdleSound(void);
   
#line 302 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void SightSound(void);
   
#line 308 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void WoundSound(void);
   
#line 314 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void DeathSound(void);
   
#line 321 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void KamikazeSoundOn(void);
   
#line 327 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void KamikazeSoundOff(void);
   
#line 337 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void BlowUpNotify(void);
   
#line 391 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void Explode(void);
   
#line 433 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
void SetSpeedsToDesiredPosition(const FLOAT3D & vPosDelta,FLOAT fPosDistance,BOOL bGoingToPlayer);
  
#line 450 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
virtual FLOAT GetAttackMoveFrequency(FLOAT fEnemyDistance);
#define  STATE_CHeadman_InitializeAttack 0x012f0000
  BOOL 
#line 464 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
InitializeAttack(const CEntityEvent &__eeInput);
#define  STATE_CHeadman_StopAttack 0x012f0001
  BOOL 
#line 471 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
StopAttack(const CEntityEvent &__eeInput);
#define  STATE_CHeadman_Fire 0x012f0002
  BOOL 
#line 476 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
Fire(const CEntityEvent &__eeInput);
  BOOL H0x012f0003_Fire_01(const CEntityEvent &__eeInput);
  BOOL H0x012f0004_Fire_02(const CEntityEvent &__eeInput);
  BOOL H0x012f0005_Fire_03(const CEntityEvent &__eeInput);
  BOOL H0x012f0006_Fire_04(const CEntityEvent &__eeInput);
  BOOL H0x012f0007_Fire_05(const CEntityEvent &__eeInput);
  BOOL H0x012f0008_Fire_06(const CEntityEvent &__eeInput);
  BOOL H0x012f0009_Fire_07(const CEntityEvent &__eeInput);
  BOOL H0x012f000a_Fire_08(const CEntityEvent &__eeInput);
  BOOL H0x012f000b_Fire_09(const CEntityEvent &__eeInput);
  BOOL H0x012f000c_Fire_10(const CEntityEvent &__eeInput);
  BOOL H0x012f000d_Fire_11(const CEntityEvent &__eeInput);
  BOOL H0x012f000e_Fire_12(const CEntityEvent &__eeInput);
#define  STATE_CHeadman_BombermanAttack 0x012f000f
  BOOL 
#line 494 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
BombermanAttack(const CEntityEvent &__eeInput);
  BOOL H0x012f0010_BombermanAttack_01(const CEntityEvent &__eeInput);
  BOOL H0x012f0011_BombermanAttack_02(const CEntityEvent &__eeInput);
  BOOL H0x012f0012_BombermanAttack_03(const CEntityEvent &__eeInput);
  BOOL H0x012f0013_BombermanAttack_04(const CEntityEvent &__eeInput);
  BOOL H0x012f0014_BombermanAttack_05(const CEntityEvent &__eeInput);
  BOOL H0x012f0015_BombermanAttack_06(const CEntityEvent &__eeInput);
  BOOL H0x012f0016_BombermanAttack_07(const CEntityEvent &__eeInput);
  BOOL H0x012f0017_BombermanAttack_08(const CEntityEvent &__eeInput);
#define  STATE_CHeadman_FirecrackerAttack 0x012f0018
  BOOL 
#line 543 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
FirecrackerAttack(const CEntityEvent &__eeInput);
  BOOL H0x012f0019_FirecrackerAttack_01(const CEntityEvent &__eeInput);
  BOOL H0x012f001a_FirecrackerAttack_02(const CEntityEvent &__eeInput);
  BOOL H0x012f001b_FirecrackerAttack_03(const CEntityEvent &__eeInput);
  BOOL H0x012f001c_FirecrackerAttack_04(const CEntityEvent &__eeInput);
  BOOL H0x012f001d_FirecrackerAttack_05(const CEntityEvent &__eeInput);
  BOOL H0x012f001e_FirecrackerAttack_06(const CEntityEvent &__eeInput);
  BOOL H0x012f001f_FirecrackerAttack_07(const CEntityEvent &__eeInput);
  BOOL H0x012f0020_FirecrackerAttack_08(const CEntityEvent &__eeInput);
  BOOL H0x012f0021_FirecrackerAttack_09(const CEntityEvent &__eeInput);
  BOOL H0x012f0022_FirecrackerAttack_10(const CEntityEvent &__eeInput);
  BOOL H0x012f0023_FirecrackerAttack_11(const CEntityEvent &__eeInput);
  BOOL H0x012f0024_FirecrackerAttack_12(const CEntityEvent &__eeInput);
  BOOL H0x012f0025_FirecrackerAttack_13(const CEntityEvent &__eeInput);
  BOOL H0x012f0026_FirecrackerAttack_14(const CEntityEvent &__eeInput);
  BOOL H0x012f0027_FirecrackerAttack_15(const CEntityEvent &__eeInput);
  BOOL H0x012f0028_FirecrackerAttack_16(const CEntityEvent &__eeInput);
#define  STATE_CHeadman_RocketmanAttack 0x012f0029
  BOOL 
#line 574 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
RocketmanAttack(const CEntityEvent &__eeInput);
  BOOL H0x012f002a_RocketmanAttack_01(const CEntityEvent &__eeInput);
  BOOL H0x012f002b_RocketmanAttack_02(const CEntityEvent &__eeInput);
  BOOL H0x012f002c_RocketmanAttack_03(const CEntityEvent &__eeInput);
  BOOL H0x012f002d_RocketmanAttack_04(const CEntityEvent &__eeInput);
#define  STATE_CHeadman_Death 0x012f002e
  BOOL 
#line 591 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
Death(const CEntityEvent &__eeInput);
  BOOL H0x012f002f_Death_01(const CEntityEvent &__eeInput);
  BOOL H0x012f0030_Death_02(const CEntityEvent &__eeInput);
#define  STATE_CHeadman_Main 1
  BOOL 
#line 612 "D:/SE1_GPL/Sources/EntitiesMP/Headman.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Headman_INCLUDED
