/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Item_INCLUDED
#define _EntitiesMP_Item_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CItem_DLLClass;
class DECL_DLL  CItem : public CMovableModelEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual const CTString &GetDescription(void) const { return m_strDescription; };
virtual BOOL IsTargetable(void) const { return TRUE; };
virtual CEntity *GetPredictionPair(void) { return m_penPrediction; };
virtual void SetPredictionPair(CEntity *penPair) { m_penPrediction = penPair; };
   virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  FLOAT m_fValue;
  FLOAT m_fRespawnTime;
  FLOAT m_fCustomRespawnTime;
  BOOL m_bRespawn;
  CEntityPointer m_penTarget;
  BOOL m_bPickupOnce;
  CSoundObject m_soPick;
  FLOAT m_fPickSoundLen;
  BOOL m_bDropped;
  INDEX m_ulPickedMask;
  BOOL m_bFloating;
  CEntityPointer m_penPrediction;
  
#line 40 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
virtual void AdjustDifficulty(void);
   
#line 45 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
void AdjustMipFactor(FLOAT & fMipFactor);
   
#line 84 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
BOOL ShowItemParticles(void);
   
#line 100 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
BOOL MarkPickedBy(CEntity * pen);
   
#line 112 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
FLOAT GetPredictionRange(void);
   
#line 119 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   
#line 149 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
void Initialize(void);
   
#line 175 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
void AddItem(ULONG ulIDModel,ULONG ulIDTexture,
#line 176 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture);
   
#line 180 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
void AddItemSpecial(INDEX iAttachmentPos,ULONG ulIDModel,ULONG ulIDTexture,
#line 181 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture);
   
#line 187 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
void AddItemAttachment(INDEX iAttachment,ULONG ulIDModel,ULONG ulIDTexture,
#line 188 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture);
   
#line 194 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
void SetItemAttachmentAnim(INDEX iAttachment,INDEX iAnim);
   
#line 203 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
void AddFlare(ULONG ulIDModel,ULONG ulIDTexture,
#line 204 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
const FLOAT3D & vPos,const FLOAT3D & vStretch);
   
#line 218 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
void StretchItem(const FLOAT3D & vStretch);
   
#line 227 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
SLONG GetUsedMemory(void);
#define  STATE_CItem_ItemCollected 0x03200000
  BOOL 
#line 245 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
ItemCollected(const CEntityEvent &__eeInput);
#define  STATE_CItem_ItemLoop 0x03200001
  BOOL 
#line 253 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
ItemLoop(const CEntityEvent &__eeInput);
  BOOL H0x03200002_ItemLoop_01(const CEntityEvent &__eeInput);
  BOOL H0x03200003_ItemLoop_02(const CEntityEvent &__eeInput);
  BOOL H0x03200004_ItemLoop_03(const CEntityEvent &__eeInput);
  BOOL H0x03200005_ItemLoop_04(const CEntityEvent &__eeInput);
  BOOL H0x03200006_ItemLoop_05(const CEntityEvent &__eeInput);
  BOOL H0x03200007_ItemLoop_06(const CEntityEvent &__eeInput);
#define  STATE_CItem_ItemReceived 0x03200008
  BOOL 
#line 283 "D:/SE1_GPL/Sources/EntitiesMP/Item.es"
ItemReceived(const CEntityEvent &__eeInput);
  BOOL H0x03200009_ItemReceived_01(const CEntityEvent &__eeInput);
  BOOL H0x0320000a_ItemReceived_02(const CEntityEvent &__eeInput);
  BOOL H0x0320000b_ItemReceived_03(const CEntityEvent &__eeInput);
  BOOL H0x0320000c_ItemReceived_04(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Item_INCLUDED
