/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 4 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"

#include "StdH.h"

#include <EntitiesMP/SummonerMarker.h>
#include <EntitiesMP/SummonerMarker_tables.h>
void CSummonerMarker::SetDefaultProperties(void) {
  m_strName = "SummonerMarker";
  m_strDescription = "SummonerMarker";
  m_fMarkerRange = 0.0f;
  CMarker::SetDefaultProperties();
}
  
#line 27 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
BOOL CSummonerMarker::MovesByTargetedRoute(CTString & strTargetProperty)const {
#line 28 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
strTargetProperty  = "Target";
#line 29 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
return TRUE ;
#line 30 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
}
  
#line 33 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
BOOL CSummonerMarker::DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const {
#line 34 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
fnmMarkerClass  = CTFILENAME  ("Classes\\SummonerMarker.ecl");
#line 35 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
strTargetProperty  = "Target";
#line 36 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
return TRUE ;
#line 37 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
}
  
#line 39 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
BOOL CSummonerMarker::IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget) 
#line 40 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
{
#line 41 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
if(slPropertyOffset  == offsetof  (CSummonerMarker  , m_penTarget ))
#line 42 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
{
#line 43 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
if(IsOfClass  (penTarget  , "SummonerMarker")){return TRUE ;}
#line 44 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
else {return FALSE ;}
#line 45 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
}
#line 46 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
return CEntity  :: IsTargetValid  (slPropertyOffset  , penTarget );
#line 47 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
}
BOOL CSummonerMarker::
#line 50 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSummonerMarker_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSummonerMarker::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 52 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
InitAsEditorModel  ();
#line 53 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 54 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 57 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
SetModel  (MODEL_SUMMONERMARKER );
#line 58 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
SetModelMainTexture  (TEXTURE_SUMMONERMARKER );
#line 60 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
Return(STATE_CURRENT,EVoid());
#line 60 "D:/SE1_GPL/Sources/EntitiesMP/SummonerMarker.es"
return TRUE; ASSERT(FALSE); return TRUE;};