/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 4 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"

#include "StdH.h"
#include "ModelsMP/Enemies/Woman/Woman.h"
#include "Models/Enemies/Headman/Headman.h"
#include "EntitiesMP/Headman.h"

#include <EntitiesMP/Woman.h>
#include <EntitiesMP/Woman_tables.h>
#line 13 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"

// info structure
static EntityInfo eiWomanStand = {
  EIBT_FLESH, 100.0f,
  0.0f, 1.55f, 0.0f,
  0.0f, 1.0f, 0.0f,
};
static EntityInfo eiWomanFly = {
  EIBT_FLESH, 80.0f,
  0.0f, 0.0f, 0.0f,
  0.0f, 0.0f, 0.0f,
};

#define FIRE_AIR      FLOAT3D(0.0f, 0.25f, -0.65f)
#define FIRE_GROUND   FLOAT3D(0.0f, 1.3f, -0.5f)
#define KAMIKAZE_ATTACH FLOAT3D(0.0f, -0.43f, -0.28f)

void CWoman::SetDefaultProperties(void) {
  m_bKamikazeCarrier = FALSE ;
  m_rKamikazeDropDistance = 40.0f;
  m_bKamikazeAttached = FALSE ;
  CEnemyFly::SetDefaultProperties();
}
  CTString CWoman::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 64 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
{
#line 65 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CTString str ;
#line 66 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(eDeath  . eLastDamage  . dmtType  == DMT_CLOSERANGE ){
#line 67 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
str  . PrintF  (TRANS  ("%s was beaten by a Scythian Harpy") , strPlayerName );
#line 68 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 69 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
str  . PrintF  (TRANS  ("A Scythian Harpy got %s spellbound") , strPlayerName );
#line 70 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 71 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return str ;
#line 72 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  const CTFileName & CWoman::GetComputerMessageName(void)const {
#line 74 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
static DECLARE_CTFILENAME  (fnm  , "Data\\Messages\\Enemies\\Woman.txt");
#line 75 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return fnm ;
#line 76 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 77 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::Precache(void) {
#line 78 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CEnemyBase  :: Precache  ();
#line 79 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PrecacheSound  (SOUND_IDLE );
#line 80 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PrecacheSound  (SOUND_SIGHT );
#line 81 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PrecacheSound  (SOUND_WOUND );
#line 82 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PrecacheSound  (SOUND_FIRE );
#line 83 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PrecacheSound  (SOUND_KICK );
#line 84 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PrecacheSound  (SOUND_DEATH );
#line 85 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_WOMAN_FIRE );
#line 86 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 89 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void * CWoman::GetEntityInfo(void) {
#line 90 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bInAir ){
#line 91 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return & eiWomanFly ;
#line 92 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 93 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return & eiWomanStand ;
#line 94 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 95 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 98 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 99 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 100 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
{
#line 102 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(! IsOfClass  (penInflictor  , "Woman")){
#line 103 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CEnemyFly  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 104 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 105 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 109 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
INDEX CWoman::AnimForDamage(FLOAT fDamage) {
#line 110 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
INDEX iAnim ;
#line 111 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bInAir ){
#line 112 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
iAnim  = WOMAN_ANIM_AIRWOUND02 ;
#line 113 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 114 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
iAnim  = WOMAN_ANIM_GROUNDWOUND04 ;
#line 115 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 116 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (iAnim  , 0);
#line 117 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return iAnim ;
#line 118 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 121 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
INDEX CWoman::AnimForDeath(void) {
#line 122 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
INDEX iAnim ;
#line 123 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bInAir ){
#line 124 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
iAnim  = WOMAN_ANIM_AIRDEATH ;
#line 125 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 126 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
iAnim  = WOMAN_ANIM_GROUNDDEATH01 ;
#line 127 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 128 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (iAnim  , 0);
#line 129 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return iAnim ;
#line 130 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 132 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FLOAT CWoman::WaitForDust(FLOAT3D & vStretch) {
#line 133 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(GetModelObject  () -> GetAnim  () == WOMAN_ANIM_AIRDEATH )
#line 134 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
{
#line 135 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
vStretch  = FLOAT3D (1 , 1 , 2) * 1.0f;
#line 136 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return 0.6f;
#line 137 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 138 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
else if(GetModelObject  () -> GetAnim  () == WOMAN_ANIM_GROUNDDEATH01 )
#line 139 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
{
#line 140 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
vStretch  = FLOAT3D (1 , 1 , 2) * 0.75f;
#line 141 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return 0.525f;
#line 142 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 143 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return - 1.0f;
#line 144 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 146 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::DeathNotify(void) {
#line 147 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
ChangeCollisionBoxIndexWhenPossible  (WOMAN_COLLISION_BOX_DEATH );
#line 148 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
en_fDensity  = 500.0f;
#line 149 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 152 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::StandingAnim(void) {
#line 153 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bInAir ){
#line 154 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_AIRSTAND  , AOF_LOOPING  | AOF_NORESTART );
#line 155 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 156 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_GROUNDSTAND  , AOF_LOOPING  | AOF_NORESTART );
#line 157 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 158 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 159 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::WalkingAnim(void) {
#line 160 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bInAir ){
#line 161 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_AIRFLY  , AOF_LOOPING  | AOF_NORESTART );
#line 162 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 163 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_GROUNDWALK  , AOF_LOOPING  | AOF_NORESTART );
#line 164 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 165 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 166 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::RunningAnim(void) {
#line 167 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bInAir ){
#line 168 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_AIRFLY  , AOF_LOOPING  | AOF_NORESTART );
#line 169 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 170 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_GROUNDRUN  , AOF_LOOPING  | AOF_NORESTART );
#line 171 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 172 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 173 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::RotatingAnim(void) {
#line 174 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bInAir ){
#line 175 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_AIRFLY  , AOF_LOOPING  | AOF_NORESTART );
#line 176 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 177 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_GROUNDWALK  , AOF_LOOPING  | AOF_NORESTART );
#line 178 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 179 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 180 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FLOAT CWoman::AirToGroundAnim(void) {
#line 181 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_AIRTOGROUND  , 0);
#line 182 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return (GetModelObject  () -> GetAnimLength  (WOMAN_ANIM_AIRTOGROUND ));
#line 183 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 184 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FLOAT CWoman::GroundToAirAnim(void) {
#line 185 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_GROUNDTOAIR  , 0);
#line 186 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return (GetModelObject  () -> GetAnimLength  (WOMAN_ANIM_GROUNDTOAIR ));
#line 187 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 188 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::ChangeCollisionToAir() {
#line 189 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
ChangeCollisionBoxIndexWhenPossible  (WOMAN_COLLISION_BOX_AIR );
#line 190 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 191 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::ChangeCollisionToGround() {
#line 192 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
ChangeCollisionBoxIndexWhenPossible  (WOMAN_COLLISION_BOX_GROUND );
#line 193 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 196 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::IdleSound(void) {
#line 197 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 198 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 199 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::SightSound(void) {
#line 200 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 201 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 202 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::WoundSound(void) {
#line 203 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 204 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 205 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::DeathSound(void) {
#line 206 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 207 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 209 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::AttachKamikaze() 
#line 210 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
{
#line 211 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
AddAttachmentToModel  (this  , * GetModelObject  () , WOMAN_ATTACHMENT_KAMIKAZE  , MODEL_HEADMAN  , TEXTURE_HEADMAN  , 0 , 0 , 0);
#line 212 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CModelObject & amo  = GetModelObject  () -> GetAttachmentModel  (WOMAN_ATTACHMENT_KAMIKAZE ) -> amo_moModelObject ;
#line 213 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
AddAttachmentToModel  (this  , amo  , HEADMAN_ATTACHMENT_BOMB_RIGHT_HAND  , MODEL_BOMB  , TEXTURE_BOMB  , 0 , 0 , 0);
#line 214 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
AddAttachmentToModel  (this  , amo  , HEADMAN_ATTACHMENT_BOMB_LEFT_HAND  , MODEL_BOMB  , TEXTURE_BOMB  , 0 , 0 , 0);
#line 215 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
amo  . PlayAnim  (HEADMAN_ANIM_KAMIKAZE_ATTACK  , AOF_LOOPING );
#line 216 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_bKamikazeAttached  = TRUE ;
#line 217 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 219 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::RemoveKamikaze() 
#line 220 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
{
#line 221 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
RemoveAttachmentFromModel  (* GetModelObject  () , WOMAN_ATTACHMENT_KAMIKAZE );
#line 222 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 224 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::DropKamikaze() 
#line 225 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
{
#line 226 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(! m_bKamikazeAttached ){return ;}
#line 228 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CEntity  * pen  = NULL ;
#line 230 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CPlacement3D pl ;
#line 231 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
pl  = GetPlacement  ();
#line 232 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
pl  . pl_PositionVector  += KAMIKAZE_ATTACH  * GetRotationMatrix  ();
#line 233 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
pen  = CreateEntity  (pl  , CLASS_HEADMAN );
#line 235 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
((CHeadman  *) & * pen ) -> m_hdtType  = HDT_KAMIKAZE ;
#line 238 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
pen  -> End  ();
#line 240 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CEnemyBase  * peb  = ((CEnemyBase  *) pen );
#line 241 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
peb  -> m_bTemplate  = FALSE ;
#line 242 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
pen  -> Initialize  ();
#line 245 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_bKamikazeAttached  = FALSE ;
#line 248 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
RemoveKamikaze  ();
#line 249 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 252 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::PreMoving() {
#line 253 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bKamikazeAttached  && m_bKamikazeCarrier ){
#line 255 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
INDEX ctMaxPlayers  = GetMaxPlayers  ();
#line 256 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CEntity  * penPlayer ;
#line 257 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
for(INDEX i  = 0;i  < ctMaxPlayers ;i  ++){
#line 258 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
penPlayer  = GetPlayerEntity  (i );
#line 259 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(penPlayer  != NULL ){
#line 260 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(DistanceTo  (this  , penPlayer ) < m_rKamikazeDropDistance  && IsVisible  (penPlayer )){
#line 261 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
DropKamikaze  ();
#line 262 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 263 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 264 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 265 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 266 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CEnemyFly  :: PreMoving  ();
#line 267 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
  
#line 269 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
void CWoman::BlowUp(void) 
#line 270 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
{
#line 271 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
DropKamikaze  ();
#line 272 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CEnemyFly  :: BlowUp  ();
#line 273 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
BOOL CWoman::
#line 280 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FlyFire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWoman_FlyFire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWoman::FlyFire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 281 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bKamikazeAttached ){Return(STATE_CURRENT,EReturn  ());return TRUE;}
#line 284 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_AIRATTACK02  , 0);
#line 285 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(0.6f);
Jump(STATE_CURRENT, 0x01400001, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x01400001_FlyFire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01400002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x01400002_FlyFire_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400002
;
#line 286 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
ShootProjectile  (PRT_WOMAN_FIRE  , FIRE_AIR  , ANGLE3D (0 , 0 , 0));
#line 287 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 288 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(0.6f);
Jump(STATE_CURRENT, 0x01400003, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x01400003_FlyFire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01400004, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x01400004_FlyFire_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400004
;
#line 289 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StandingAnim  ();
#line 290 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(FRnd  () / 2 + _pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x01400005, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x01400005_FlyFire_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01400006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x01400006_FlyFire_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400006
;
#line 292 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Return(STATE_CURRENT,EReturn  ());
#line 292 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWoman::
#line 295 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FlyHit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWoman_FlyHit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWoman::FlyHit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 296 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bKamikazeAttached ){Return(STATE_CURRENT,EReturn  ());return TRUE;}
#line 299 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(CalcDist  (m_penEnemy ) <= 5.0f){
#line 301 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CMovableEntity  * pen  = (CMovableEntity  *) & * m_penEnemy ;
#line 302 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
CContentType  & ctDn  = pen  -> en_pwoWorld  -> wo_actContentTypes  [ pen  -> en_iDnContent  ];
#line 303 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
BOOL bEnemySwimming  = ! (ctDn  . ct_ulFlags  & CTF_BREATHABLE_LUNGS );
#line 304 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(bEnemySwimming ){
#line 305 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Jump(STATE_CURRENT, STATE_CWoman_FlyFire, TRUE, EVoid());return TRUE;
#line 306 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}else {
#line 307 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Jump(STATE_CURRENT, STATE_CWoman_FlyOnEnemy, TRUE, EVoid());return TRUE;
#line 308 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 309 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 312 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fShootTime  = _pTimer  -> CurrentTick  () + 0.25f;
#line 313 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Return(STATE_CURRENT,EReturn  ());
#line 313 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWoman::
#line 319 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Death(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWoman_Death
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWoman::Death expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 320 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
DropKamikaze  ();
#line 321 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Jump(STATE_CURRENT, STATE_CEnemyFly_Death, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWoman::
#line 324 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
AirToGround(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWoman_AirToGround
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWoman::AirToGround expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 325 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
DropKamikaze  ();
#line 326 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Jump(STATE_CURRENT, STATE_CEnemyFly_AirToGround, FALSE, EVoid  ());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWoman::
#line 329 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FlyOnEnemy(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWoman_FlyOnEnemy
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWoman::FlyOnEnemy expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 330 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_AIRATTACK01  , 0);
#line 333 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FLOAT3D vDir  = PlayerDestinationPos  ();
#line 334 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
vDir  = (vDir  - GetPlacement  () . pl_PositionVector ) . Normalize  ();
#line 335 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
vDir  *= ! GetRotationMatrix  ();
#line 336 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
vDir  *= m_fFlyCloseRunSpeed  * 1.9f;
#line 337 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetDesiredTranslation  (vDir );
#line 338 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PlaySound  (m_soSound  , SOUND_KICK  , SOF_3D );
#line 341 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SpawnReminder  (this  , 0.9f , 0);
#line 342 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_iChargeHitAnimation  = WOMAN_ANIM_AIRATTACK01 ;
#line 343 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fChargeHitDamage  = 20.0f;
#line 344 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fChargeHitAngle  = 0.0f;
#line 345 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fChargeHitSpeed  = 10.0f;
#line 346 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
STATE_CEnemyBase_ChargeHitEnemy, FALSE;
Jump(STATE_CURRENT, 0x0140000b, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x0140000b_FlyOnEnemy_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0140000b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_ChargeHitEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0140000c, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CWoman::H0x0140000c_FlyOnEnemy_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0140000c
const EReturn&__e= (EReturn&)__eeInput;
;
#line 348 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StandingAnim  ();
#line 349 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(0.3f);
Jump(STATE_CURRENT, 0x0140000d, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x0140000d_FlyOnEnemy_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0140000d
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0140000e, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x0140000e_FlyOnEnemy_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0140000e
;
#line 350 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Return(STATE_CURRENT,EReturn  ());
#line 350 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWoman::
#line 353 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
GroundFire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWoman_GroundFire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWoman::GroundFire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 355 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_GROUNDATTACK02  , 0);
#line 356 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(0.3f);
Jump(STATE_CURRENT, 0x01400010, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x01400010_GroundFire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400010
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01400011, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x01400011_GroundFire_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400011
;
#line 357 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
ShootProjectile  (PRT_WOMAN_FIRE  , FIRE_GROUND  , ANGLE3D (0 , 0 , 0));
#line 358 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 359 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(0.3f);
Jump(STATE_CURRENT, 0x01400012, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x01400012_GroundFire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400012
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01400013, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x01400013_GroundFire_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400013
;
#line 360 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StandingAnim  ();
#line 361 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(FRnd  () / 2 + _pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x01400014, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x01400014_GroundFire_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400014
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01400015, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x01400015_GroundFire_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400015
;
#line 363 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Return(STATE_CURRENT,EReturn  ());
#line 363 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWoman::
#line 366 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
GroundHit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWoman_GroundHit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWoman::GroundHit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 367 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StartModelAnim  (WOMAN_ANIM_GROUNDATTACK01  , 0);
#line 370 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
FLOAT3D vDir  = (m_penEnemy  -> GetPlacement  () . pl_PositionVector  - 
#line 371 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
GetPlacement  () . pl_PositionVector ) . Normalize  ();
#line 372 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
vDir  *= ! GetRotationMatrix  ();
#line 373 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
vDir  *= m_fCloseRunSpeed  * 1.75f;
#line 374 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
vDir  (2) = 2.5f;
#line 375 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetDesiredTranslation  (vDir );
#line 376 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
PlaySound  (m_soSound  , SOUND_KICK  , SOF_3D );
#line 379 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SpawnReminder  (this  , 0.9f , 0);
#line 380 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_iChargeHitAnimation  = WOMAN_ANIM_GROUNDATTACK01 ;
#line 381 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fChargeHitDamage  = 20.0f;
#line 382 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fChargeHitAngle  = 0.0f;
#line 383 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fChargeHitSpeed  = 10.0f;
#line 384 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
STATE_CEnemyBase_ChargeHitEnemy, FALSE;
Jump(STATE_CURRENT, 0x01400017, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x01400017_GroundHit_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400017
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_ChargeHitEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01400018, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CWoman::H0x01400018_GroundHit_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400018
const EReturn&__e= (EReturn&)__eeInput;
;
#line 386 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
StandingAnim  ();
#line 387 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(0.3f);
Jump(STATE_CURRENT, 0x01400019, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x01400019_GroundHit_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01400019
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0140001a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x0140001a_GroundHit_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0140001a
;
#line 388 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Return(STATE_CURRENT,EReturn  ());
#line 388 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CWoman::
#line 396 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CWoman_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CWoman::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 398 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
InitAsModel  ();
#line 399 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 400 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetCollisionFlags  (ECF_MODEL );
#line 401 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 402 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetHealth  (100.0f);
#line 403 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fMaxHealth  = 100.0f;
#line 404 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
en_tmMaxHoldBreath  = 5.0f;
#line 405 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
en_fDensity  = 2000.0f;
#line 407 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_sptType  = SPT_FEATHER ;
#line 410 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetModel  (MODEL_WOMAN );
#line 411 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetModelMainTexture  (TEXTURE_WOMAN );
#line 413 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fWalkSpeed  = FRnd  () + 1.5f;
#line 414 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_aWalkRotateSpeed  = FRnd  () * 10.0f + 25.0f;
#line 415 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fAttackRunSpeed  = FRnd  () * 2.0f + 9.0f;
#line 416 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_aAttackRotateSpeed  = FRnd  () * 50 + 245.0f;
#line 417 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fCloseRunSpeed  = FRnd  () * 2.0f + 4.0f;
#line 418 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_aCloseRotateSpeed  = FRnd  () * 50 + 245.0f;
#line 420 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fAttackDistance  = 50.0f;
#line 421 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fCloseDistance  = 5.0f;
#line 422 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fStopDistance  = 0.0f;
#line 423 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fAttackFireTime  = 3.0f;
#line 424 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fCloseFireTime  = 2.0f;
#line 425 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fIgnoreRange  = 200.0f;
#line 427 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyWalkSpeed  = FRnd  () / 2 + 1.0f;
#line 428 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_aFlyWalkRotateSpeed  = FRnd  () * 10.0f + 25.0f;
#line 429 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyAttackRunSpeed  = FRnd  () * 2.0f + 10.0f;
#line 430 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_aFlyAttackRotateSpeed  = FRnd  () * 25 + 150.0f;
#line 431 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyCloseRunSpeed  = FRnd  () * 2.0f + 10.0f;
#line 432 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_aFlyCloseRotateSpeed  = FRnd  () * 50 + 500.0f;
#line 433 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fGroundToAirSpeed  = m_fFlyCloseRunSpeed ;
#line 434 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fAirToGroundSpeed  = m_fFlyCloseRunSpeed ;
#line 435 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fAirToGroundMin  = 0.1f;
#line 436 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fAirToGroundMax  = 0.1f;
#line 438 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyAttackDistance  = 50.0f;
#line 439 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyCloseDistance  = 12.5f;
#line 440 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyStopDistance  = 0.0f;
#line 441 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyAttackFireTime  = 3.0f;
#line 442 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyCloseFireTime  = 2.0f;
#line 443 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fFlyIgnoreRange  = 200.0f;
#line 445 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fBlowUpAmount  = 100.0f;
#line 446 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fBodyParts  = 4;
#line 447 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_fDamageWounded  = 20.0f;
#line 448 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
m_iScore  = 1000;
#line 450 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
if(m_bKamikazeCarrier ){
#line 451 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
AttachKamikaze  ();
#line 452 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
}
#line 454 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
SetTimerAfter(0.05f);
Jump(STATE_CURRENT, 0x0140001b, FALSE, EBegin());return TRUE;}BOOL CWoman::H0x0140001b_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0140001b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0140001c, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CWoman::H0x0140001c_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0140001c
;
#line 457 "D:/SE1_GPL/Sources/EntitiesMP/Woman.es"
Jump(STATE_CURRENT, STATE_CEnemyFly_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};