/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_WorldBase_INCLUDED
#define _EntitiesMP_WorldBase_INCLUDED 1
#include <EntitiesMP\FogMarker.h>
#include <EntitiesMP\HazeMarker.h>
#include <EntitiesMP\MirrorMarker.h>
#include <EntitiesMP\GradientMarker.h>
extern "C" DECL_DLL CDLLEntityClass CWorldBase_DLLClass;
class CWorldBase : public CEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual const CTString &GetDescription(void) const { return m_strDescription; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  CTString m_strDescription;
  BOOL m_bZoning;
  BOOL m_bBackground;
  BOOL m_bAnchored;
  CEntityPointer m_penGravity0;
  CEntityPointer m_penGravity1;
  CEntityPointer m_penGravity2;
  CEntityPointer m_penGravity3;
  CEntityPointer m_penGravity4;
  CEntityPointer m_penGravity5;
  CEntityPointer m_penGravity6;
  CEntityPointer m_penGravity7;
  CEntityPointer m_penGravity8;
  CEntityPointer m_penGravity9;
  CEntityPointer m_penFog0;
  CEntityPointer m_penFog1;
  CEntityPointer m_penFog2;
  CEntityPointer m_penFog3;
  CEntityPointer m_penFog4;
  CEntityPointer m_penFog5;
  CEntityPointer m_penFog6;
  CEntityPointer m_penFog7;
  CEntityPointer m_penFog8;
  CEntityPointer m_penFog9;
  CEntityPointer m_penHaze0;
  CEntityPointer m_penHaze1;
  CEntityPointer m_penHaze2;
  CEntityPointer m_penHaze3;
  CEntityPointer m_penHaze4;
  CEntityPointer m_penMirror0;
  CEntityPointer m_penMirror1;
  CEntityPointer m_penMirror2;
  CEntityPointer m_penMirror3;
  CEntityPointer m_penMirror4;
  CEntityPointer m_penGradient0;
  CEntityPointer m_penGradient1;
  CEntityPointer m_penGradient2;
  CEntityPointer m_penGradient3;
  CEntityPointer m_penGradient4;
  CEntityPointer m_penGradient5;
  CEntityPointer m_penGradient6;
  CEntityPointer m_penGradient7;
  CEntityPointer m_penGradient8;
  CEntityPointer m_penGradient9;
  CEntityPointer m_penGradient10;
  CEntityPointer m_penGradient11;
  CEntityPointer m_penGradient12;
  CEntityPointer m_penGradient13;
  CEntityPointer m_penGradient14;
  CEntityPointer m_penGradient15;
  CEntityPointer m_penGradient16;
  CEntityPointer m_penGradient17;
  CEntityPointer m_penGradient18;
  CEntityPointer m_penGradient19;
  ULONG m_cbClassificationBits;
  ULONG m_vbVisibilityBits;
  FLOAT m_fOpacity;
   
#line 1003 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
ULONG GetVisTweaks(void);
   
#line 1009 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
BOOL IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget);
   
#line 1064 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
const CTString & GetForceName(INDEX iForce);
   
#line 1086 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
void GetForce(INDEX iForce,const FLOAT3D & vPoint,
#line 1087 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
CForceStrength & fsGravity,CForceStrength & fsField);
   
#line 1109 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
CEntity * GetForceController(INDEX iForce);
   
#line 1125 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
const CTString & GetFogName(INDEX iFog);
   
#line 1141 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
BOOL GetFog(INDEX iFog,class CFogParameters & fpFog);
   
#line 1155 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
const CTString & GetHazeName(INDEX iHaze);
   
#line 1172 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
BOOL GetHaze(INDEX iHaze,class CHazeParameters & hpHaze,FLOAT3D & vViewDir);
   
#line 1186 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
const CTString & GetMirrorName(INDEX iMirror);
   
#line 1220 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
BOOL GetMirror(INDEX iMirror,class CMirrorParameters & mpMirror);
   
#line 1242 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
const CTString & GetGradientName(INDEX iGradient);
   
#line 1258 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
void UncacheShadowsForGradient(class CGradientMarker * penDiscard);
   
#line 1272 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
BOOL GetGradient(INDEX iGradient,class CGradientParameters & fpGradient);
   
#line 1285 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
BOOL HandleEvent(const CEntityEvent & ee);
   
#line 1300 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
SLONG GetUsedMemory(void);
   
#line 1312 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
FLOAT GetOpacity(void);
#define  STATE_CWorldBase_Main 1
  BOOL 
#line 1322 "D:/SE1_GPL/Sources/EntitiesMP/WorldBase.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_WorldBase_INCLUDED
