/* Copyright (c) 2002-2012 Croteam Ltd. All rights reserved. */

// Animation names
#define HANDWITHTORCH_ANIM_DEFAULT_ANIMATION 0
#define HANDWITHTORCH_ANIM_LIGHTERFIRE 1
#define HANDWITHTORCH_ANIM_LIGHTERACTIVATE 2
#define HANDWITHTORCH_ANIM_LIGHTERDEACTIVATE 3
#define HANDWITHTORCH_ANIM_LIGHTERWAIT1 4
#define HANDWITHTORCH_ANIM_LIGHTERWAIT2 5
#define HANDWITHTORCH_ANIM_LIGHTERWAIT3 6
#define HANDWITHTORCH_ANIM_LIGHTERWAIT4 7
#define HANDWITHTORCH_ANIM_LIGHTERWAIT5 8

// Color names

// Patch names

// Names of collision boxes
#define HANDWITHTORCH_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define HANDWITHTORCH_ATTACHMENT_TORCH 0
#define HANDWITHTORCH_ATTACHMENT_FLAME 1

// Sound names
